# Generated by Django 4.1.3 on 2023-01-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='short',
            field=models.CharField(default='', max_length=50),
        ),
    ]
