# Generated by Django 4.1.3 on 2023-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatter_web', '0002_genre_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
